### ISSUE TITLE
User attributes

### ISSUE THREAD

**Issue by adamdelaney** [ITS-UofIowa/intranet.pharmacy.uiowa.edu#4]
ITS will contact DNA about getting additional user attributes such as first and last name.

**Comment by adamdelaney** [comment]
This looks like we can map saml attributes to a user using hook_simplesaml_auth_pre_login(). See: https://github.com/ITS-UofIowa/uiowa_acquia_authentication/blob/1e9eefe216335d17c0e4b05a26573c1d40d19405/uiowa_acquia_authentication.module#L158.

**Comment by adamdelaney** [comment]
> Hi Brian,

Yes, we can release any of the name attributes if you're able to map them on your end. If this is something you decide to proceed with, let us know by contacting our on-call box (its-dna-identity-services@uiowa.edu) and we'll make the required modifications.

Best,
Michael

**Comment by briand44** [comment]
The DNA team released the name attributes and these are being mapped in hook_simplesamlphp_auth_pre_login().
