### ISSUE TITLE
Phase 1 requirements

### ISSUE THREAD

**Issue by adamdelaney** [ITS-UofIowa/intranet.pharmacy.uiowa.edu#9]
- ~Remove top photo - this is theme config~ 
- Drop downs for menus/navigation 
    - Resources For Faculty, Staff, Grad Students 
- Reduce size for News items 
- ~Ability to add and modify navigation - they have menu access~ 
- ~Ability to add content within navigation/menu structure - they can add basic pages to the menu system~
- Remove Drupal Admin bar at top? 
- ~Ability for everyone to add an Event or Brief~ 
- ~Remove "Internal" from Events and Briefs~ 
- ~External/public events should be imported into the Events and Briefs box~ 
- ~Ability to modify the "Social" links - this is a menu~

**Comment by briand44** [comment]
I've got the events feed importer setup. I think the only thing that I am aware of at this point related to events is we need to style canceled events (I'm already outputting the text and a class) and to style the new fields on the full event node. I tried styling the canceled events but running into problems with outdated versions of node.js and npm.
